taba7-algorivew/front

- src/components/CustomSidebar.tsx
- src/layouts/ReviewLayout.tsx
- src/styles/review.css
사이드바가 고정으로 유지됩니다.
global.css, CustomSidebar.tsx를 수정했습니다.
> 사이드바 기능 수정, 사이드바가 고정으로 유지됩니다.

- src/components/Feedback.tsx
- src/pages/ReviewPage.tsx
ReviewPage.tsx에서 Feedback.tsx로의 데이터를 넘기는 부분에서 
"필요한 데이터들을 다 넘기지 않았던 부분"을 수정해서 
"필요한 데이터들을 다 전달하도록" 수정했습니다.
> 챗봇 기능 디버그, 요청 데이터 problemInfo and sourceCode가 제대로 전달되지 않던 현상을 수정했습니다.

- src/api/HistoriesApi.tsx
- src/components/Chatbot.tsx
- src/components/Feedback.tsx
src/api/Histories.tsx 파일을 수정했습니다.
히스토리 조회 실패 이유는 Histories.tsx 파일에서 서버 url 주소가 다른 서버로 고정으로 설정되어 있어 발생한 문제입니다.
해당 문제를 조치하고자 BaseApi.tsx를 사용하도록 수정했습니다.
> 히스토리 조회 실패 이슈 해결, edit the src/api/Histories.tsx

- src/api/BaseApi.tsx
- src/api/HistoriesApi.tsx
- src/api/ReviewRequestApi.tsx
- src/api/SolutionApi.tsx
BaseApi에서 서버 주소만 바꾸면 모든 API주소가 통일되도록 변경하였습니다. 버그없는것까지 확인완료했습니다.
> Fix: 모든 API파일을 BaseApi.tsx만 서버 주소를 수정하면 적용되도록 변경

- package-lock.json
- package.json
- src/api/BaseApi.tsx
- src/api/FeedbackApi.tsx
- src/api/SolutionApi.tsx
- src/components/Feedback.tsx
- src/components/SolutionCode.tsx
- src/pages/ReviewPage.tsx
Add : solution code를 받아오기 위한 API(GET,POST)와 response에 대한 TorF여부에 따라 U…I가 다르게 나오도록 기능 추가 - 아직 POST응답에 대한 UI액션이 되지 않는 이슈가 있음. 이후 new review를 누를때 solution code부분이 clear되지 않음.
> ADD : SolutionApi, SolutionCode, Feedback코드에 솔루션 코드 받아오기 위한 기능 추가

- src/components/Feedback.tsx
- src/components/History.tsx
- src/components/SolutionCode.tsx
- src/styles/global.css
History, Feedback, SolutionCode 등에 있던 각종 타입오류와 declare but never read에 대한 오류 수정
> Fix : 각종 타입 오류 해결

- src/api/BaseApi.tsx
- src/components/Feedback.tsx
- src/components/HighLight.tsx
- src/components/SolutionCode.tsx
- src/pages/RegisterPage.tsx
ADD: PASS or FAIL indicating color on title + Closing Action of titles
> ADD: PASS or FAIL indicating color on title + Closing Action of titles

- src/components/Feedback.tsx
- src/components/SolutionCode.tsx
모범 답안을 조회한 채로, 
다른 히스토리를 조회하면 이전 히스토리의 모범 답안이 보이던 에러가 있었습니다.
해당 에러에 대해 수정했습니다.
> 피드백, 모범답안 기능 수정

- src/api/BaseApi.tsx
- src/api/HistoriesApi.tsx
- src/components/CodeEditor.tsx
- src/components/Feedback.tsx
- src/components/HighLight.tsx
- src/components/SolutionCode.tsx
- src/pages/ReviewPage.tsx
Fix : 하이라이트 색상이 is_passed여부에 따라 변경되지 않던 오류 해결
> Fix : 하이라이트 색상이 is_passed여부에 따라 변경되지 않던 오류 해결

- src/components/CodeEditor.tsx
- src/components/SolutionCode.tsx
- src/styles/CodeEditor.css
- src/styles/review.css
소스코드와 결과 코드 출력 부분에 대해 디자인을 했습니다.
스크롤바가 얇아졌고, 코드 출력 부분에 패딩을 제거했습니다.
> scroll bar design

- src/components/CustomSidebar.tsx
- src/components/History.tsx
- src/layouts/ReviewLayout.tsx
- src/pages/ReviewPage.tsx
사이드바에 히스토리 생성 즉시 보일 수 있도록 기능 구현했습니다.
아직은 백엔드와 테스트를 실시하지 않은 상태입니다만, 백엔드 작업자와 협업 이후 코드 수정해서 다시 풀리퀘스트 올리겠습니다.
> 사이드바 히스토리 바로 보이는 기능 구현

- src/components/Feedback.tsx
- src/pages/ReviewPage.tsx
run review와 review again을 해왔을 때는 값을 잘 받아오는것을 확인했으나, 히스토리를 통해 가져온 값들에 대해서는 아직 확인해보지 못했습니다. 참고 부탁드립니다.
> Add : revision값을 받아오면 feedback 우측 상단에 값을 띄워주는 기능 추가

- src/api/BaseApi.tsx
- src/components/CodeEditor.tsx
- src/components/Feedback.tsx
- src/components/SolutionCode.tsx
- src/pages/ReviewPage.tsx
- src/styles/global.css
- src/styles/review.css
리뷰 페이지가 한 눈에 들어오도록 수정했습니다.
code-input, code-ouput의 패딩값 수정,
각 요소 별 마진값 조정
> 리뷰 페이지 디자인 대폭 변경

- src/components/CustomSidebar.tsx
- src/components/Feedback.tsx
- src/components/History.tsx
- src/components/UrlOrFileUploader.tsx
- src/layouts/ReviewLayout.tsx
- src/pages/ReviewPage.tsx
- src/styles/feedback.css
- src/styles/global.css
- src/styles/homepage.css
- src/styles/review.css
- src/styles/solution.css
- vite.config.ts
디자인 미적용 부분들 해소 - css파일을 한 곳으로 정리하면서 발생
1) 리뷰 상세 색상 미적용 해소
2) 리뷰 페이지 중상단 버튼들[new review, url, image, ...]을 class로 구분지어 디자인을 적용하게 함
디자인 변경
1) 사이드바 히스토리 수정 아이콘 변경
2) 사이드바 히스토리 크기 변경
환경설정
1) 지정하지 않아도 default로서 작용한 값들이지만, 명시함으로서 정확히 알게 했습니다.
> 환경설정, 디자인 변경 및 구성, 디자인 에러 해소

- src/components/CodeEditor.tsx
- src/components/Feedback.tsx
- src/components/SolutionCode.tsx
- src/pages/ReviewPage.tsx
- src/styles/feedback.css
- src/styles/review.css
리뷰 페이지의 디자인이 일부 수정되었습니다.
1) n번째 리뷰 위치 변경 - 기존 [모범 답안] 탭 우측에 위치해있던 것을 리뷰 페이지 중상단(버튼들 있는 곳) 우측에 배치했습니다.
2) 코드미러 비율 조정 - 라인 넘버 배경과 크기, 코드 폰트 크기를 조정했습니다.
3) [Run Review] 버튼 패딩 조정
> 리뷰 페이지 디자인 작업

- src/App.tsx
- src/api/BaseApi.tsx
- src/components/CustomSidebar.tsx
- src/components/HighLight.tsx
- src/components/History.tsx
- src/pages/ReviewPage.tsx
app.tsx, customSidebar.tsx, ReviewLayout.tsx, History.tsx에 발생하는 타입 에러 해결
> Fix : 모든 타입오류 해결

- src/pages/ReviewPage.tsx
재리뷰 시 사이드바 재출력이 되지 않던 버그를 수정했습니다.
> 사이드바 버그 수정

- src/api/BaseApi.tsx
- src/components/SolutionCode.tsx
Fix: solutioncode.tsx에 대한 타입 에러 수정 및 수정으로 인한 오류 없음 확인
> Fix: solutioncode.tsx에 대한 타입 에러 수정 및 수정으로 인한 오류 없음 확인

- src/api/BaseApi.tsx
- src/components/CompleteDialog.tsx
- src/styles/review.css
- src/styles/solution.css
> 리뷰 완성 dialog 디자인 수정

- src/components/CodeEditor.tsx
- src/components/SolutionCode.tsx
- src/pages/ReviewPage.tsx
- src/styles/review.css
디자인 요소들만 수정이 되었습니다.
1) "+New Review" -> "+새로운 문제 생성"
2) "Run Review" -> "리뷰 받기"
3) "Review Again" -> "다시 리뷰 받기"
4) url 입력폼 너비 축소
5) 인풋, 모범 코드 너비 제한 수정
> New Review, run Review, Review Again 버튼 명 수정 및 모범답안 추력 시 길이 확장 오류 수정

- src/pages/HomePage.tsx
- src/styles/homepage.css
> Fix: homepage 섹션 로직 분리

- src/pages/HomePage.tsx
[리뷰 시작하기] 버튼을 누르면, 로그인 페이지로 이동하는 기능을 추가했습니다.
> 인트로 페이지 - [리뷰 시작하기] 버튼 기능 추가

- .dockerignore
- src/api/BaseApi.tsx
- src/components/CustomEditor.tsx
- src/pages/HomePage.tsx
- src/styles/homepage.css
- src/styles/homepage_Intro.css
Add : 홈페이지 인트로 스타일 추가 + homepage_Intro.css, CustomEditor.tsx파일 추가
> Add : 홈페이지 인트로 스타일 추가 + homepage_Intro.css, CustomEditor.tsx파일 추가

- src/api/BaseApi.tsx
- src/pages/HomePage.tsx
- src/pages/TutorialPage.tsx
- src/styles/homepage.css
- src/styles/tutorial.css
Fix : 홈페이지 디자인 최종 변경 및 튜토리얼 페이지 삭제필요부분 수정. 힘들렁
> Fix : 홈페이지 디자인 최종 변경 및 튜토리얼 페이지 삭제필요부분 수정
